package nvidiasmi

type Nvidia_smi_log struct {
	Pci_domain                                                  string   `json:"pci_domain" xml:"gpu>pci>pci_domain"`
	Rx_util                                                     string   `json:"rx_util" xml:"gpu>pci>rx_util"`
	Processes                                                   string   `json:"processes" xml:"gpu>processes"`
	Device_memory                                               string   `json:"device_memory" xml:"gpu>ecc_errors>volatile>double_bit>device_memory"`
	L2_cacheSingle_bitVolatileEcc_errorsGpu                     string   `json:"l2_cache_single_bit_volatile_ecc_errors_gpu" xml:"gpu>ecc_errors>volatile>single_bit>l2_cache"`
	Texture_memoryDouble_bitAggregateEcc_errorsGpu              string   `json:"texture_memory_double_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>double_bit>texture_memory"`
	Retired_page_addressesDouble_bit_retirementRetired_pagesGpu string   `json:"retired_page_addresses_double_bit_retirement_retired_pages_gpu" xml:"gpu>retired_pages>double_bit_retirement>retired_page_addresses"`
	Free                                                        string   `json:"free" xml:"gpu>bar1_memory_usage>free"`
	Register_file                                               string   `json:"register_file" xml:"gpu>ecc_errors>volatile>double_bit>register_file"`
	Multigpu_board                                              string   `json:"multigpu_board" xml:"gpu>multigpu_board"`
	Power_draw                                                  string   `json:"power_draw" xml:"gpu>power_readings>power_draw"`
	Pending_gom                                                 string   `json:"pending_gom" xml:"gpu>gpu_operation_mode>pending_gom"`
	Gpu_temp                                                    string   `json:"gpu_temp" xml:"gpu>temperature>gpu_temp"`
	Sm_clockMax_clocksGpu                                       string   `json:"sm_clock_max_clocks_gpu" xml:"gpu>max_clocks>sm_clock"`
	TotalSingle_bitVolatileEcc_errorsGpu                        string   `json:"total_single_bit_volatile_ecc_errors_gpu" xml:"gpu>ecc_errors>volatile>single_bit>total"`
	Graphics_clock                                              string   `json:"graphics_clock" xml:"gpu>clocks>graphics_clock"`
	TotalBar1_memory_usageGpu                                   string   `json:"total_bar_1_memory_usage_gpu" xml:"gpu>bar1_memory_usage>total"`
	Img_version                                                 string   `json:"img_version" xml:"gpu>inforom_version>img_version"`
	Fan_speed                                                   string   `json:"fan_speed" xml:"gpu>fan_speed"`
	L1_cache                                                    string   `json:"l1_cache" xml:"gpu>ecc_errors>volatile>double_bit>l1_cache"`
	Gpu                                                         Gpu      `json:"gpu" xml:"gpu"`
	Mem_clock                                                   string   `json:"mem_clock" xml:"gpu>clocks>mem_clock"`
	Retired_countDouble_bit_retirementRetired_pagesGpu          string   `json:"retired_count_double_bit_retirement_retired_pages_gpu" xml:"gpu>retired_pages>double_bit_retirement>retired_count"`
	Display_active                                              string   `json:"display_active" xml:"gpu>display_active"`
	Total                                                       string   `json:"total" xml:"gpu>ecc_errors>volatile>double_bit>total"`
	Device_memorySingle_bitVolatileEcc_errorsGpu                string   `json:"device_memory_single_bit_volatile_ecc_errors_gpu" xml:"gpu>ecc_errors>volatile>single_bit>device_memory"`
	Sm_clock                                                    string   `json:"sm_clock" xml:"gpu>clocks>sm_clock"`
	Enforced_power_limit                                        string   `json:"enforced_power_limit" xml:"gpu>power_readings>enforced_power_limit"`
	Pci_bus_id                                                  string   `json:"pci_bus_id" xml:"gpu>pci>pci_bus_id"`
	Mem_clockDefault_applications_clocksGpu                     string   `json:"mem_clock_default_applications_clocks_gpu" xml:"gpu>default_applications_clocks>mem_clock"`
	Vbios_version                                               string   `json:"vbios_version" xml:"gpu>vbios_version"`
	Pci_device_id                                               string   `json:"pci_device_id" xml:"gpu>pci>pci_device_id"`
	Bridge_chip_fw                                              string   `json:"bridge_chip_fw" xml:"gpu>pci>pci_bridge_chip>bridge_chip_fw"`
	Pending_ecc                                                 string   `json:"pending_ecc" xml:"gpu>ecc_mode>pending_ecc"`
	L1_cacheSingle_bitVolatileEcc_errorsGpu                     string   `json:"l1_cache_single_bit_volatile_ecc_errors_gpu" xml:"gpu>ecc_errors>volatile>single_bit>l1_cache"`
	Power_limit                                                 string   `json:"power_limit" xml:"gpu>power_readings>power_limit"`
	Max_link_width                                              string   `json:"max_link_width" xml:"gpu>pci>pci_gpu_link_info>link_widths>max_link_width"`
	L2_cache                                                    string   `json:"l2_cache" xml:"gpu>ecc_errors>volatile>double_bit>l2_cache"`
	TotalDouble_bitAggregateEcc_errorsGpu                       string   `json:"total_double_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>double_bit>total"`
	Retired_page_addresses                                      string   `json:"retired_page_addresses" xml:"gpu>retired_pages>multiple_single_bit_retirement>retired_page_addresses"`
	Oem_object                                                  string   `json:"oem_object" xml:"gpu>inforom_version>oem_object"`
	Auto_boost                                                  string   `json:"auto_boost" xml:"gpu>clock_policy>auto_boost"`
	Register_fileSingle_bitAggregateEcc_errorsGpu               string   `json:"register_file_single_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>single_bit>register_file"`
	UsedFb_memory_usageGpu                                      string   `json:"used_fb_memory_usage_gpu" xml:"gpu>fb_memory_usage>used"`
	Encoder_util                                                string   `json:"encoder_util" xml:"gpu>utilization>encoder_util"`
	Minor_number                                                string   `json:"minor_number" xml:"gpu>minor_number"`
	Register_fileSingle_bitVolatileEcc_errorsGpu                string   `json:"register_file_single_bit_volatile_ecc_errors_gpu" xml:"gpu>ecc_errors>volatile>single_bit>register_file"`
	Device_memoryDouble_bitAggregateEcc_errorsGpu               string   `json:"device_memory_double_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>double_bit>device_memory"`
	Graphics_clockDefault_applications_clocksGpu                string   `json:"graphics_clock_default_applications_clocks_gpu" xml:"gpu>default_applications_clocks>graphics_clock"`
	Texture_memorySingle_bitVolatileEcc_errorsGpu               string   `json:"texture_memory_single_bit_volatile_ecc_errors_gpu" xml:"gpu>ecc_errors>volatile>single_bit>texture_memory"`
	L2_cacheSingle_bitAggregateEcc_errorsGpu                    string   `json:"l2_cache_single_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>single_bit>l2_cache"`
	Device_memorySingle_bitAggregateEcc_errorsGpu               string   `json:"device_memory_single_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>single_bit>device_memory"`
	Pending_retirement                                          string   `json:"pending_retirement" xml:"gpu>retired_pages>pending_retirement"`
	Default_power_limit                                         string   `json:"default_power_limit" xml:"gpu>power_readings>default_power_limit"`
	Accounting_mode                                             string   `json:"accounting_mode" xml:"gpu>accounting_mode"`
	Clocks_throttle_reason_gpu_idle                             string   `json:"clocks_throttle_reason_gpu_idle" xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_gpu_idle"`
	Register_fileDouble_bitAggregateEcc_errorsGpu               string   `json:"register_file_double_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>double_bit>register_file"`
	Current_gom                                                 string   `json:"current_gom" xml:"gpu>gpu_operation_mode>current_gom"`
	Gpu_temp_max_threshold                                      string   `json:"gpu_temp_max_threshold" xml:"gpu>temperature>gpu_temp_max_threshold"`
	Product_brand                                               string   `json:"product_brand" xml:"gpu>product_brand"`
	Max_link_gen                                                string   `json:"max_link_gen" xml:"gpu>pci>pci_gpu_link_info>pcie_gen>max_link_gen"`
	Ecc_object                                                  string   `json:"ecc_object" xml:"gpu>inforom_version>ecc_object"`
	Board_id                                                    string   `json:"board_id" xml:"gpu>board_id"`
	Max_power_limit                                             string   `json:"max_power_limit" xml:"gpu>power_readings>max_power_limit"`
	Power_state                                                 string   `json:"power_state" xml:"gpu>power_readings>power_state"`
	Min_power_limit                                             string   `json:"min_power_limit" xml:"gpu>power_readings>min_power_limit"`
	Driver_version                                              string   `json:"driver_version" xml:"driver_version"`
	Graphics_clockApplications_clocksGpu                        string   `json:"graphics_clock_applications_clocks_gpu" xml:"gpu>applications_clocks>graphics_clock"`
	Performance_state                                           string   `json:"performance_state" xml:"gpu>performance_state"`
	Memory_util                                                 string   `json:"memory_util" xml:"gpu>utilization>memory_util"`
	Auto_boost_default                                          string   `json:"auto_boost_default" xml:"gpu>clock_policy>auto_boost_default"`
	Power_management                                            string   `json:"power_management" xml:"gpu>power_readings>power_management"`
	Mem_clockApplications_clocksGpu                             string   `json:"mem_clock_applications_clocks_gpu" xml:"gpu>applications_clocks>mem_clock"`
	FreeFb_memory_usageGpu                                      string   `json:"free_fb_memory_usage_gpu" xml:"gpu>fb_memory_usage>free"`
	Pci_sub_system_id                                           string   `json:"pci_sub_system_id" xml:"gpu>pci>pci_sub_system_id"`
	Current_link_width                                          string   `json:"current_link_width" xml:"gpu>pci>pci_gpu_link_info>link_widths>current_link_width"`
	Tx_util                                                     string   `json:"tx_util" xml:"gpu>pci>tx_util"`
	Product_name                                                string   `json:"product_name" xml:"gpu>product_name"`
	Value                                                       []string `json:"value" xml:"gpu>supported_clocks>supported_mem_clock>value"`
	Attached_gpus                                               string   `json:"attached_gpus" xml:"attached_gpus"`
	Current_ecc                                                 string   `json:"current_ecc" xml:"gpu>ecc_mode>current_ecc"`
	Texture_memory                                              string   `json:"texture_memory" xml:"gpu>ecc_errors>volatile>double_bit>texture_memory"`
	Gpu_util                                                    string   `json:"gpu_util" xml:"gpu>utilization>gpu_util"`
	Accounting_mode_buffer_size                                 string   `json:"accounting_mode_buffer_size" xml:"gpu>accounting_mode_buffer_size"`
	Texture_memorySingle_bitAggregateEcc_errorsGpu              string   `json:"texture_memory_single_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>single_bit>texture_memory"`
	L1_cacheDouble_bitAggregateEcc_errorsGpu                    string   `json:"l1_cache_double_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>double_bit>l1_cache"`
	Pci_device                                                  string   `json:"pci_device" xml:"gpu>pci>pci_device"`
	Replay_counter                                              string   `json:"replay_counter" xml:"gpu>pci>replay_counter"`
	Uuid                                                        string   `json:"uuid" xml:"gpu>uuid"`
	Used                                                        string   `json:"used" xml:"gpu>bar1_memory_usage>used"`
	Current_dm                                                  string   `json:"current_dm" xml:"gpu>driver_model>current_dm"`
	Pending_dm                                                  string   `json:"pending_dm" xml:"gpu>driver_model>pending_dm"`
	Persistence_mode                                            string   `json:"persistence_mode" xml:"gpu>persistence_mode"`
	Pci_bus                                                     string   `json:"pci_bus" xml:"gpu>pci>pci_bus"`
	Clocks_throttle_reason_applications_clocks_setting          string   `json:"clocks_throttle_reason_applications_clocks_setting" xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_applications_clocks_setting"`
	Clocks_throttle_reason_sw_power_cap                         string   `json:"clocks_throttle_reason_sw_power_cap" xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_sw_power_cap"`
	Decoder_util                                                string   `json:"decoder_util" xml:"gpu>utilization>decoder_util"`
	Retired_count                                               string   `json:"retired_count" xml:"gpu>retired_pages>multiple_single_bit_retirement>retired_count"`
	Serial                                                      string   `json:"serial" xml:"gpu>serial"`
	TotalSingle_bitAggregateEcc_errorsGpu                       string   `json:"total_single_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>single_bit>total"`
	Compute_mode                                                string   `json:"compute_mode" xml:"gpu>compute_mode"`
	Timestamp                                                   string   `json:"timestamp" xml:"timestamp"`
	Graphics_clockMax_clocksGpu                                 string   `json:"graphics_clock_max_clocks_gpu" xml:"gpu>max_clocks>graphics_clock"`
	Bridge_chip_type                                            string   `json:"bridge_chip_type" xml:"gpu>pci>pci_bridge_chip>bridge_chip_type"`
	Pwr_object                                                  string   `json:"pwr_object" xml:"gpu>inforom_version>pwr_object"`
	L1_cacheSingle_bitAggregateEcc_errorsGpu                    string   `json:"l1_cache_single_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>single_bit>l1_cache"`
	L2_cacheDouble_bitAggregateEcc_errorsGpu                    string   `json:"l2_cache_double_bit_aggregate_ecc_errors_gpu" xml:"gpu>ecc_errors>aggregate>double_bit>l2_cache"`
	Gpu_temp_slow_threshold                                     string   `json:"gpu_temp_slow_threshold" xml:"gpu>temperature>gpu_temp_slow_threshold"`
	Mem_clockMax_clocksGpu                                      string   `json:"mem_clock_max_clocks_gpu" xml:"gpu>max_clocks>mem_clock"`
	TotalFb_memory_usageGpu                                     string   `json:"total_fb_memory_usage_gpu" xml:"gpu>fb_memory_usage>total"`
	Current_link_gen                                            string   `json:"current_link_gen" xml:"gpu>pci>pci_gpu_link_info>pcie_gen>current_link_gen"`
	Clocks_throttle_reason_hw_slowdown                          string   `json:"clocks_throttle_reason_hw_slowdown" xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_hw_slowdown"`
	Display_mode                                                string   `json:"display_mode" xml:"gpu>display_mode"`
	Clocks_throttle_reason_unknown                              string   `json:"clocks_throttle_reason_unknown" xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_unknown"`
	Accounted_processes                                         string   `json:"accounted_processes" xml:"gpu>accounted_processes"`
	Supported_graphics_clock                                    []string `json:"supported_graphics_clock" xml:"gpu>supported_clocks>supported_mem_clock>supported_graphics_clock"`
}

type Gpu struct {
	Id string `json:"id" xml:"id,attr"`
}

