package nvidiasmi

type GPU struct {
	ID                                                     string   `xml:"id,attr" json:"id"`
	MemClockClocksGpu                                      string   `xml:"gpu>clocks>mem_clock" json:"mem_clock_clocks_gpu"`
	L1Cache                                                string   `xml:"gpu>ecc_errors>volatile>single_bit>l1_cache" json:"l_1_cache"`
	ProductName                                            string   `xml:"gpu>product_name" json:"product_name"`
	FreeFbMemoryUsageGpu                                   string   `xml:"gpu>fb_memory_usage>free" json:"free_fb_memory_usage_gpu"`
	PowerState                                             string   `xml:"gpu>power_readings>power_state" json:"power_state"`
	Free                                                   string   `xml:"gpu>bar1_memory_usage>free" json:"free"`
	RetiredCountDoubleBitRetirementRetiredPagesGpu         string   `xml:"gpu>retired_pages>double_bit_retirement>retired_count" json:"retired_count_double_bit_retirement_retired_pages_gpu"`
	ClocksThrottleReasonUnknown                            string   `xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_unknown" json:"clocks_throttle_reason_unknown"`
	ClocksThrottleReasonApplicationsClocksSetting          string   `xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_applications_clocks_setting" json:"clocks_throttle_reason_applications_clocks_setting"`
	Processes                                              string   `xml:"gpu>processes" json:"processes"`
	MemClockApplicationsClocksGpu                          string   `xml:"gpu>applications_clocks>mem_clock" json:"mem_clock_applications_clocks_gpu"`
	L2CacheSingleBitAggregateEccErrorsGpu                  string   `xml:"gpu>ecc_errors>aggregate>single_bit>l2_cache" json:"l_2_cache_single_bit_aggregate_ecc_errors_gpu"`
	CurrentLinkGen                                         string   `xml:"gpu>pci>pci_gpu_link_info>pcie_gen>current_link_gen" json:"current_link_gen"`
	TotalSingleBitVolatileEccErrorsGpu                     string   `xml:"gpu>ecc_errors>volatile>single_bit>total" json:"total_single_bit_volatile_ecc_errors_gpu"`
	TextureMemoryDoubleBitVolatileEccErrorsGpu             string   `xml:"gpu>ecc_errors>volatile>double_bit>texture_memory" json:"texture_memory_double_bit_volatile_ecc_errors_gpu"`
	L1CacheSingleBitAggregateEccErrorsGpu                  string   `xml:"gpu>ecc_errors>aggregate>single_bit>l1_cache" json:"l_1_cache_single_bit_aggregate_ecc_errors_gpu"`
	PendingGom                                             string   `xml:"gpu>gpu_operation_mode>pending_gom" json:"pending_gom"`
	AutoBoostDefault                                       string   `xml:"gpu>clock_policy>auto_boost_default" json:"auto_boost_default"`
	GraphicsClockApplicationsClocksGpu                     string   `xml:"gpu>applications_clocks>graphics_clock" json:"graphics_clock_applications_clocks_gpu"`
	PciBusID                                               string   `xml:"gpu>pci>pci_bus_id" json:"pci_bus_id"`
	PowerManagement                                        string   `xml:"gpu>power_readings>power_management" json:"power_management"`
	DeviceMemoryDoubleBitAggregateEccErrorsGpu             string   `xml:"gpu>ecc_errors>aggregate>double_bit>device_memory" json:"device_memory_double_bit_aggregate_ecc_errors_gpu"`
	BoardID                                                string   `xml:"gpu>board_id" json:"board_id"`
	DeviceMemoryDoubleBitVolatileEccErrorsGpu              string   `xml:"gpu>ecc_errors>volatile>double_bit>device_memory" json:"device_memory_double_bit_volatile_ecc_errors_gpu"`
	SupportedGraphicsClock                                 []string `xml:"gpu>supported_clocks>supported_mem_clock>supported_graphics_clock" json:"supported_graphics_clock"`
	PersistenceMode                                        string   `xml:"gpu>persistence_mode" json:"persistence_mode"`
	MemClock                                               string   `xml:"gpu>max_clocks>mem_clock" json:"mem_clock"`
	GraphicsClockClocksGpu                                 string   `xml:"gpu>clocks>graphics_clock" json:"graphics_clock_clocks_gpu"`
	Used                                                   string   `xml:"gpu>bar1_memory_usage>used" json:"used"`
	ImgVersion                                             string   `xml:"gpu>inforom_version>img_version" json:"img_version"`
	UsedFbMemoryUsageGpu                                   string   `xml:"gpu>fb_memory_usage>used" json:"used_fb_memory_usage_gpu"`
	TotalDoubleBitAggregateEccErrorsGpu                    string   `xml:"gpu>ecc_errors>aggregate>double_bit>total" json:"total_double_bit_aggregate_ecc_errors_gpu"`
	MinorNumber                                            string   `xml:"gpu>minor_number" json:"minor_number"`
	ProductBrand                                           string   `xml:"gpu>product_brand" json:"product_brand"`
	GraphicsClockDefaultApplicationsClocksGpu              string   `xml:"gpu>default_applications_clocks>graphics_clock" json:"graphics_clock_default_applications_clocks_gpu"`
	TotalFbMemoryUsageGpu                                  string   `xml:"gpu>fb_memory_usage>total" json:"total_fb_memory_usage_gpu"`
	RegisterFileDoubleBitVolatileEccErrorsGpu              string   `xml:"gpu>ecc_errors>volatile>double_bit>register_file" json:"register_file_double_bit_volatile_ecc_errors_gpu"`
	MinPowerLimit                                          string   `xml:"gpu>power_readings>min_power_limit" json:"min_power_limit"`
	TxUtil                                                 string   `xml:"gpu>pci>tx_util" json:"tx_util"`
	TextureMemory                                          string   `xml:"gpu>ecc_errors>volatile>single_bit>texture_memory" json:"texture_memory"`
	RegisterFileDoubleBitAggregateEccErrorsGpu             string   `xml:"gpu>ecc_errors>aggregate>double_bit>register_file" json:"register_file_double_bit_aggregate_ecc_errors_gpu"`
	PerformanceState                                       string   `xml:"gpu>performance_state" json:"performance_state"`
	CurrentDm                                              string   `xml:"gpu>driver_model>current_dm" json:"current_dm"`
	PciDeviceID                                            string   `xml:"gpu>pci>pci_device_id" json:"pci_device_id"`
	AccountedProcesses                                     string   `xml:"gpu>accounted_processes" json:"accounted_processes"`
	PendingRetirement                                      string   `xml:"gpu>retired_pages>pending_retirement" json:"pending_retirement"`
	TotalDoubleBitVolatileEccErrorsGpu                     string   `xml:"gpu>ecc_errors>volatile>double_bit>total" json:"total_double_bit_volatile_ecc_errors_gpu"`
	UUID                                                   string   `xml:"gpu>uuid" json:"uuid"`
	PowerLimit                                             string   `xml:"gpu>power_readings>power_limit" json:"power_limit"`
	ClocksThrottleReasonHwSlowdown                         string   `xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_hw_slowdown" json:"clocks_throttle_reason_hw_slowdown"`
	BridgeChipFw                                           string   `xml:"gpu>pci>pci_bridge_chip>bridge_chip_fw" json:"bridge_chip_fw"`
	ReplayCounter                                          string   `xml:"gpu>pci>replay_counter" json:"replay_counter"`
	L2CacheDoubleBitAggregateEccErrorsGpu                  string   `xml:"gpu>ecc_errors>aggregate>double_bit>l2_cache" json:"l_2_cache_double_bit_aggregate_ecc_errors_gpu"`
	ComputeMode                                            string   `xml:"gpu>compute_mode" json:"compute_mode"`
	FanSpeed                                               string   `xml:"gpu>fan_speed" json:"fan_speed"`
	Total                                                  string   `xml:"gpu>bar1_memory_usage>total" json:"total"`
	SmClock                                                string   `xml:"gpu>max_clocks>sm_clock" json:"sm_clock"`
	RxUtil                                                 string   `xml:"gpu>pci>rx_util" json:"rx_util"`
	GraphicsClock                                          string   `xml:"gpu>max_clocks>graphics_clock" json:"graphics_clock"`
	PwrObject                                              string   `xml:"gpu>inforom_version>pwr_object" json:"pwr_object"`
	PciBus                                                 string   `xml:"gpu>pci>pci_bus" json:"pci_bus"`
	DecoderUtil                                            string   `xml:"gpu>utilization>decoder_util" json:"decoder_util"`
	PciSubSystemID                                         string   `xml:"gpu>pci>pci_sub_system_id" json:"pci_sub_system_id"`
	MaxLinkGen                                             string   `xml:"gpu>pci>pci_gpu_link_info>pcie_gen>max_link_gen" json:"max_link_gen"`
	BridgeChipType                                         string   `xml:"gpu>pci>pci_bridge_chip>bridge_chip_type" json:"bridge_chip_type"`
	SmClockClocksGpu                                       string   `xml:"gpu>clocks>sm_clock" json:"sm_clock_clocks_gpu"`
	CurrentEcc                                             string   `xml:"gpu>ecc_mode>current_ecc" json:"current_ecc"`
	PowerDraw                                              string   `xml:"gpu>power_readings>power_draw" json:"power_draw"`
	CurrentLinkWidth                                       string   `xml:"gpu>pci>pci_gpu_link_info>link_widths>current_link_width" json:"current_link_width"`
	AutoBoost                                              string   `xml:"gpu>clock_policy>auto_boost" json:"auto_boost"`
	GpuUtil                                                string   `xml:"gpu>utilization>gpu_util" json:"gpu_util"`
	PciDevice                                              string   `xml:"gpu>pci>pci_device" json:"pci_device"`
	RegisterFile                                           string   `xml:"gpu>ecc_errors>volatile>single_bit>register_file" json:"register_file"`
	L2Cache                                                string   `xml:"gpu>ecc_errors>volatile>single_bit>l2_cache" json:"l_2_cache"`
	L1CacheDoubleBitAggregateEccErrorsGpu                  string   `xml:"gpu>ecc_errors>aggregate>double_bit>l1_cache" json:"l_1_cache_double_bit_aggregate_ecc_errors_gpu"`
	RetiredCount                                           string   `xml:"gpu>retired_pages>multiple_single_bit_retirement>retired_count" json:"retired_count"`
	PendingDm                                              string   `xml:"gpu>driver_model>pending_dm" json:"pending_dm"`
	AccountingModeBufferSize                               string   `xml:"gpu>accounting_mode_buffer_size" json:"accounting_mode_buffer_size"`
	GpuTempSlowThreshold                                   string   `xml:"gpu>temperature>gpu_temp_slow_threshold" json:"gpu_temp_slow_threshold"`
	OemObject                                              string   `xml:"gpu>inforom_version>oem_object" json:"oem_object"`
	TextureMemorySingleBitAggregateEccErrorsGpu            string   `xml:"gpu>ecc_errors>aggregate>single_bit>texture_memory" json:"texture_memory_single_bit_aggregate_ecc_errors_gpu"`
	RegisterFileSingleBitAggregateEccErrorsGpu             string   `xml:"gpu>ecc_errors>aggregate>single_bit>register_file" json:"register_file_single_bit_aggregate_ecc_errors_gpu"`
	MaxLinkWidth                                           string   `xml:"gpu>pci>pci_gpu_link_info>link_widths>max_link_width" json:"max_link_width"`
	TextureMemoryDoubleBitAggregateEccErrorsGpu            string   `xml:"gpu>ecc_errors>aggregate>double_bit>texture_memory" json:"texture_memory_double_bit_aggregate_ecc_errors_gpu"`
	ClocksThrottleReasonGpuIdle                            string   `xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_gpu_idle" json:"clocks_throttle_reason_gpu_idle"`
	MultigpuBoard                                          string   `xml:"gpu>multigpu_board" json:"multigpu_board"`
	GpuTempMaxThreshold                                    string   `xml:"gpu>temperature>gpu_temp_max_threshold" json:"gpu_temp_max_threshold"`
	MaxPowerLimit                                          string   `xml:"gpu>power_readings>max_power_limit" json:"max_power_limit"`
	L2CacheDoubleBitVolatileEccErrorsGpu                   string   `xml:"gpu>ecc_errors>volatile>double_bit>l2_cache" json:"l_2_cache_double_bit_volatile_ecc_errors_gpu"`
	PciDomain                                              string   `xml:"gpu>pci>pci_domain" json:"pci_domain"`
	MemClockDefaultApplicationsClocksGpu                   string   `xml:"gpu>default_applications_clocks>mem_clock" json:"mem_clock_default_applications_clocks_gpu"`
	VbiosVersion                                           string   `xml:"gpu>vbios_version" json:"vbios_version"`
	RetiredPageAddresses                                   string   `xml:"gpu>retired_pages>multiple_single_bit_retirement>retired_page_addresses" json:"retired_page_addresses"`
	GpuTemp                                                string   `xml:"gpu>temperature>gpu_temp" json:"gpu_temp"`
	AccountingMode                                         string   `xml:"gpu>accounting_mode" json:"accounting_mode"`
	L1CacheDoubleBitVolatileEccErrorsGpu                   string   `xml:"gpu>ecc_errors>volatile>double_bit>l1_cache" json:"l_1_cache_double_bit_volatile_ecc_errors_gpu"`
	DeviceMemorySingleBitAggregateEccErrorsGpu             string   `xml:"gpu>ecc_errors>aggregate>single_bit>device_memory" json:"device_memory_single_bit_aggregate_ecc_errors_gpu"`
	DisplayActive                                          string   `xml:"gpu>display_active" json:"display_active"`
	DefaultPowerLimit                                      string   `xml:"gpu>power_readings>default_power_limit" json:"default_power_limit"`
	EncoderUtil                                            string   `xml:"gpu>utilization>encoder_util" json:"encoder_util"`
	Serial                                                 string   `xml:"gpu>serial" json:"serial"`
	EnforcedPowerLimit                                     string   `xml:"gpu>power_readings>enforced_power_limit" json:"enforced_power_limit"`
	RetiredPageAddressesDoubleBitRetirementRetiredPagesGpu string   `xml:"gpu>retired_pages>double_bit_retirement>retired_page_addresses" json:"retired_page_addresses_double_bit_retirement_retired_pages_gpu"`
	EccObject                                              string   `xml:"gpu>inforom_version>ecc_object" json:"ecc_object"`
	Value                                                  []string `xml:"gpu>supported_clocks>supported_mem_clock>value" json:"value"`
	DisplayMode                                            string   `xml:"gpu>display_mode" json:"display_mode"`
	DeviceMemory                                           string   `xml:"gpu>ecc_errors>volatile>single_bit>device_memory" json:"device_memory"`
	PendingEcc                                             string   `xml:"gpu>ecc_mode>pending_ecc" json:"pending_ecc"`
	ClocksThrottleReasonSwPowerCap                         string   `xml:"gpu>clocks_throttle_reasons>clocks_throttle_reason_sw_power_cap" json:"clocks_throttle_reason_sw_power_cap"`
	TotalSingleBitAggregateEccErrorsGpu                    string   `xml:"gpu>ecc_errors>aggregate>single_bit>total" json:"total_single_bit_aggregate_ecc_errors_gpu"`
	CurrentGom                                             string   `xml:"gpu>gpu_operation_mode>current_gom" json:"current_gom"`
	MemoryUtil                                             string   `xml:"gpu>utilization>memory_util" json:"memory_util"`
}

type NvidiaSmi struct {
	Timestamp     string `xml:"timestamp" json:"timestamp"`
	DriverVersion string `xml:"driver_version" json:"driver_version"`
	AttachedGpus  string `xml:"attached_gpus" json:"attached_gpus"`
	GPUS          []GPU  `xml:"gpus" json:"gpus"`
}
